package com.quran.labs.androidquran.common.ui.core
import androidx.compose.ui.graphics.Color

val lightPrimary = Color(0xFF00696F)
val lightOnPrimary = Color(0xFFFFFFFF)
val lightPrimaryContainer = Color(0xFF79F5FF)
val lightOnPrimaryContainer = Color(0xFF002022)
val lightSecondary = Color(0xFF4A6365)
val lightOnSecondary = Color(0xFFFFFFFF)
val lightSecondaryContainer = Color(0xFFCCE8EA)
val lightOnSecondaryContainer = Color(0xFF051F21)
val lightTertiary = Color(0xFF4F5F7D)
val lightOnTertiary = Color(0xFFFFFFFF)
val lightTertiaryContainer = Color(0xFFD7E2FF)
val lightOnTertiaryContainer = Color(0xFF0A1B36)
val lightError = Color(0xFFBA1A1A)
val lightErrorContainer = Color(0xFFFFDAD6)
val lightOnError = Color(0xFFFFFFFF)
val lightOnErrorContainer = Color(0xFF410002)
val lightBackground = Color(0xFFFAFDFC)
val lightOnBackground = Color(0xFF191C1C)
val lightSurface = Color(0xFFFAFDFC)
val lightOnSurface = Color(0xFF191C1C)
val lightSurfaceVariant = Color(0xFFDAE4E5)
val lightOnSurfaceVariant = Color(0xFF3F4849)
val lightOutline = Color(0xFF6F797A)
val lightInverseOnSurface = Color(0xFFEFF1F1)
val lightInverseSurface = Color(0xFF2D3131)
val lightInversePrimary = Color(0xFF4DD9E4)
val lightShadow = Color(0xFF000000)
val lightSurfaceTint = Color(0xFF00696F)

val darkPrimary = Color(0xFF4DD9E4)
val darkOnPrimary = Color(0xFF00363A)
val darkPrimaryContainer = Color(0xFF004F54)
val darkOnPrimaryContainer = Color(0xFF79F5FF)
val darkSecondary = Color(0xFFB1CBCE)
val darkOnSecondary = Color(0xFF1B3436)
val darkSecondaryContainer = Color(0xFF324B4D)
val darkOnSecondaryContainer = Color(0xFFCCE8EA)
val darkTertiary = Color(0xFFB7C7EA)
val darkOnTertiary = Color(0xFF21304C)
val darkTertiaryContainer = Color(0xFF374764)
val darkOnTertiaryContainer = Color(0xFFD7E2FF)
val darkError = Color(0xFFFFB4AB)
val darkErrorContainer = Color(0xFF93000A)
val darkOnError = Color(0xFF690005)
val darkOnErrorContainer = Color(0xFFFFDAD6)
val darkBackground = Color(0xFF191C1C)
val darkOnBackground = Color(0xFFE0E3E3)
val darkSurface = Color(0xFF191C1C)
val darkOnSurface = Color(0xFFE0E3E3)
val darkSurfaceVariant = Color(0xFF3F4849)
val darkOnSurfaceVariant = Color(0xFFBEC8C9)
val darkOutline = Color(0xFF899393)
val darkInverseOnSurface = Color(0xFF191C1C)
val darkInverseSurface = Color(0xFFE0E3E3)
val darkInversePrimary = Color(0xFF00696F)
val darkShadow = Color(0xFF000000)
val darkSurfaceTint = Color(0xFF4DD9E4)

// generated with a seed of #ff1b6b71
